galaxy_info:
  author: David Marthy
  description: role for installing ElasticSearch
  company:

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 2.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - xenial
  - name: Debian
    versions:
    - stretch
    - wheezy

  galaxy_tags: []

dependencies: []