---
# defaults file for metricbeat
beats_kibana_url: "http://localhost:5601"
beats_elasticsearch_url: "http://localhost:9200"
beats_logging_level: debug
beats_pgsql_module_setup: false
beats_pgsql_module_hosts: ''
beats_pgsql_module_user: ''
beats_pgsql_module_pass: ''
beats_apache_module_setup: false