---
# tasks file for elastic

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  static: no

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  static: no 

- name: Install ElasticSearch
  package: 
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items: '{{ packages }}'

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch

- name: Start Elasticsearch
  systemd: 
    name: elasticsearch 
    state: started
    enabled: yes

- name: Make sure Elasticsearch is running before proceeding
  wait_for: 
    host: '{{ elasticsearch_network_host }}' 
    port: '{{ elasticsearch_http_port }}' 
    delay: 3 
    timeout: 300
